## view 改变形状

In [1]:
import torch

tensor :torch.Tensor = torch.tensor([[1,2,3,4,5], [6, 7, 8, 9, 10]])
print(tensor)

print(tensor.view(5, 2))

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])


In [1]:
# 现在这个 tensor 代表一个 2 个批次，每个批次 6 个向量元素的矩阵
tensor = torch.tensor([[1,2,3,4,5, 6], [7, 8, 9, 10, 11, 12]])
# 保持批次不变, 改变每个批次的向量的形状
tensor.view(-1, 3, 2)

NameError: name 'torch' is not defined

下面两个代码块详细说明了矩阵计算中指定 dim 是如何进行的

In [9]:
X = torch.tensor([[1,2,3,4,5, 6], [7, 8, 9, 10, 11, 12]], dtype=torch.float)
print(len(X.shape))
print(X.mean(dim=0))

2
tensor([4., 5., 6., 7., 8., 9.])


In [11]:
X = torch.tensor([[[1,2,3], [4,5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=torch.float)
print(X)
print(X.shape)
X_mean = X.mean(dim=1)
print(X_mean.shape)
print(X_mean)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])
torch.Size([2, 3])
tensor([[ 2.5000,  3.5000,  4.5000],
        [ 8.5000,  9.5000, 10.5000]])


In [15]:
conv_trans = torch.nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=3, padding=0)

# 创建一个 1x5 的矩阵
x = torch.tensor([[1, 2, 3, 4, 5]], dtype=torch.float32)
print(x.shape)
# 设置卷积核权重        
conv_trans.weight.data = torch.tensor([[[1.0, 2.0, 3.0]]])

# 转置卷积运算
y = conv_trans(x)
print(y)

torch.Size([1, 5])
tensor([[ 0.6967,  3.6967,  9.6967, 15.6967, 21.6967, 21.6967, 14.6967]],
       grad_fn=<SqueezeBackward1>)


In [8]:
import torch
import torch.nn as nn

input = torch.ones(1, 1, 4) # input [[[1, 1, 1, 1]]]
# 注意这里是有一个 bias 测试准确值的时候一定要有去掉这个 bias
t_conv = nn.ConvTranspose1d(
    in_channels=1,
    out_channels=1,
    stride=1,
    kernel_size=3,
    bias=False
)
t_conv.weight.data = torch.tensor(data=[[[1, 2, 3]]], dtype=torch.float)
print(t_conv(input)) # output [[[1., 2., 4., 2., 4., 2., 4., 2., 3.]]]


tensor([[[1., 3., 6., 6., 5., 3.]]], grad_fn=<ConvolutionBackward0>)
